#!/usr/bin/env python3
"""Convert assets/flappy.gif to 20x14 monochrome ACME masks (requires Pillow)."""
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
image = Image.open(ROOT / 'assets/flappy.gif')
assert image.size == (20, 14) and image.n_frames == 4
lines = ['; Generated by tools/import_bird.py from assets/flappy.gif.',
         '; Four 20x14 masks: three bytes per row, low four bits padded with zero.']
for frame in range(image.n_frames):
    image.seek(frame)
    assert image.info['duration'] == 100
    rgba = image.convert('RGBA')
    lines.append(f'BIRD_MASK_{frame}:')
    for y in range(14):
        bits = [sum((128 >> bit) for bit in range(8)
                    if byte * 8 + bit < 20 and rgba.getpixel((byte * 8 + bit, y))[3])
                for byte in range(3)]
        lines.append('    !byte ' + ', '.join(f'${value:02x}' for value in bits))
(ROOT / 'src/bird_masks.inc').write_text('\n'.join(lines) + '\n')
