initialise_bird:
    jsr render_bird
    rts

; Clear before shifting the world map so the bird stays screen-relative and
; never leaves behind glyphs in columns moved by the scroll update.
clear_bird:
    lda #GLYPH_SKY
    sta SCREEN_RAM + (BIRD_SCREEN_ROW * SCREEN_COLUMNS) + BIRD_SCREEN_COLUMN
    sta SCREEN_RAM + (BIRD_SCREEN_ROW * SCREEN_COLUMNS) + BIRD_SCREEN_COLUMN + 1
    sta SCREEN_RAM + ((BIRD_SCREEN_ROW + 1) * SCREEN_COLUMNS) + BIRD_SCREEN_COLUMN
    sta SCREEN_RAM + ((BIRD_SCREEN_ROW + 1) * SCREEN_COLUMNS) + BIRD_SCREEN_COLUMN + 1
    lda #TED_SKY_COLOR
    sta COLOR_RAM + (BIRD_SCREEN_ROW * SCREEN_COLUMNS) + BIRD_SCREEN_COLUMN
    sta COLOR_RAM + (BIRD_SCREEN_ROW * SCREEN_COLUMNS) + BIRD_SCREEN_COLUMN + 1
    sta COLOR_RAM + ((BIRD_SCREEN_ROW + 1) * SCREEN_COLUMNS) + BIRD_SCREEN_COLUMN
    sta COLOR_RAM + ((BIRD_SCREEN_ROW + 1) * SCREEN_COLUMNS) + BIRD_SCREEN_COLUMN + 1
    rts

render_bird:
    lda #GLYPH_BIRD_TOP_LEFT
    sta SCREEN_RAM + (BIRD_SCREEN_ROW * SCREEN_COLUMNS) + BIRD_SCREEN_COLUMN
    lda #GLYPH_BIRD_TOP_RIGHT
    sta SCREEN_RAM + (BIRD_SCREEN_ROW * SCREEN_COLUMNS) + BIRD_SCREEN_COLUMN + 1
    lda #GLYPH_BIRD_BOTTOM_LEFT
    sta SCREEN_RAM + ((BIRD_SCREEN_ROW + 1) * SCREEN_COLUMNS) + BIRD_SCREEN_COLUMN
    lda #GLYPH_BIRD_BOTTOM_RIGHT
    sta SCREEN_RAM + ((BIRD_SCREEN_ROW + 1) * SCREEN_COLUMNS) + BIRD_SCREEN_COLUMN + 1
    lda #TED_GROUND_COLOR
    sta COLOR_RAM + (BIRD_SCREEN_ROW * SCREEN_COLUMNS) + BIRD_SCREEN_COLUMN
    sta COLOR_RAM + (BIRD_SCREEN_ROW * SCREEN_COLUMNS) + BIRD_SCREEN_COLUMN + 1
    sta COLOR_RAM + ((BIRD_SCREEN_ROW + 1) * SCREEN_COLUMNS) + BIRD_SCREEN_COLUMN
    sta COLOR_RAM + ((BIRD_SCREEN_ROW + 1) * SCREEN_COLUMNS) + BIRD_SCREEN_COLUMN + 1
    rts
