initialise_bird:
    lda #0
    sta BIRD_Y_FRACTION
    sta BIRD_VELOCITY_FRACTION
    sta BIRD_VELOCITY
    lda #BIRD_START_Y
    sta BIRD_Y_POSITION
    jsr render_bird
    rts

update_bird_physics:
    lda FLAP_PRESSED
    beq apply_gravity
    lda #0
    sta BIRD_VELOCITY_FRACTION
    lda #BIRD_FLAP_VELOCITY
    sta BIRD_VELOCITY
    jmp update_bird_position

apply_gravity:
    clc
    lda BIRD_VELOCITY_FRACTION
    adc #BIRD_GRAVITY
    sta BIRD_VELOCITY_FRACTION
    lda BIRD_VELOCITY
    adc #0
    cmp #BIRD_MAX_FALL_SPEED
    bcc store_velocity
    lda #BIRD_MAX_FALL_SPEED
store_velocity:
    sta BIRD_VELOCITY

update_bird_position:
    clc
    lda BIRD_Y_FRACTION
    adc BIRD_VELOCITY_FRACTION
    sta BIRD_Y_FRACTION
    lda BIRD_Y_POSITION
    adc BIRD_VELOCITY
    sta BIRD_Y_POSITION
    rts

; Clear before shifting the world map so the bird stays screen-relative and
; never leaves behind glyphs in columns moved by the scroll update.
clear_bird:
    lda #GLYPH_SKY
    sta SCREEN_RAM + (BIRD_SCREEN_ROW * SCREEN_COLUMNS) + BIRD_SCREEN_COLUMN
    sta SCREEN_RAM + (BIRD_SCREEN_ROW * SCREEN_COLUMNS) + BIRD_SCREEN_COLUMN + 1
    sta SCREEN_RAM + ((BIRD_SCREEN_ROW + 1) * SCREEN_COLUMNS) + BIRD_SCREEN_COLUMN
    sta SCREEN_RAM + ((BIRD_SCREEN_ROW + 1) * SCREEN_COLUMNS) + BIRD_SCREEN_COLUMN + 1
    lda #TED_SKY_COLOR
    sta COLOR_RAM + (BIRD_SCREEN_ROW * SCREEN_COLUMNS) + BIRD_SCREEN_COLUMN
    sta COLOR_RAM + (BIRD_SCREEN_ROW * SCREEN_COLUMNS) + BIRD_SCREEN_COLUMN + 1
    sta COLOR_RAM + ((BIRD_SCREEN_ROW + 1) * SCREEN_COLUMNS) + BIRD_SCREEN_COLUMN
    sta COLOR_RAM + ((BIRD_SCREEN_ROW + 1) * SCREEN_COLUMNS) + BIRD_SCREEN_COLUMN + 1
    rts

render_bird:
    lda #GLYPH_BIRD_TOP_LEFT
    sta SCREEN_RAM + (BIRD_SCREEN_ROW * SCREEN_COLUMNS) + BIRD_SCREEN_COLUMN
    lda #GLYPH_BIRD_TOP_RIGHT
    sta SCREEN_RAM + (BIRD_SCREEN_ROW * SCREEN_COLUMNS) + BIRD_SCREEN_COLUMN + 1
    lda #GLYPH_BIRD_BOTTOM_LEFT
    sta SCREEN_RAM + ((BIRD_SCREEN_ROW + 1) * SCREEN_COLUMNS) + BIRD_SCREEN_COLUMN
    lda #GLYPH_BIRD_BOTTOM_RIGHT
    sta SCREEN_RAM + ((BIRD_SCREEN_ROW + 1) * SCREEN_COLUMNS) + BIRD_SCREEN_COLUMN + 1
    lda #TED_GROUND_COLOR
    sta COLOR_RAM + (BIRD_SCREEN_ROW * SCREEN_COLUMNS) + BIRD_SCREEN_COLUMN
    sta COLOR_RAM + (BIRD_SCREEN_ROW * SCREEN_COLUMNS) + BIRD_SCREEN_COLUMN + 1
    sta COLOR_RAM + ((BIRD_SCREEN_ROW + 1) * SCREEN_COLUMNS) + BIRD_SCREEN_COLUMN
    sta COLOR_RAM + ((BIRD_SCREEN_ROW + 1) * SCREEN_COLUMNS) + BIRD_SCREEN_COLUMN + 1
    rts
